### ISSUE TITLE
Crash after restart

### ISSUE THREAD

**Issue by Fusl** [cofyc/dnscrypt-wrapper#42]
I'm not sure if this is a bug in my setup or if this is a dnscrypt-wrapper related bug, bug here we go:

My dnscrypt-wrapper keeps crashing AFTER I kill the previous process which listened on the exact same IP+Port with exact same configuration:

```
root@fvz-rec-hk-nt-01:~# /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:443 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -VVV
[31760] 02 Jul 12:15:31.087 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74
[31760] 02 Jul 12:15:31.116 [debug] [udp_request.c:308] client to proxy cb
[31760] 02 Jul 12:15:31.228 [debug] [udp_request.c:308] client to proxy cb
[31760] 02 Jul 12:15:31.381 [debug] [udp_request.c:308] client to proxy cb
[31760] 02 Jul 12:15:31.384 [debug] [udp_request.c:308] client to proxy cb
[...]
[31760] 02 Jul 12:15:34.558 [debug] [udp_request.c:444] resolver to proxy cb
[31760] 02 Jul 12:15:34.558 [debug] [udp_request.c:444] resolver to proxy cb
[31760] 02 Jul 12:15:34.628 [debug] [udp_request.c:308] client to proxy cb
[31760] 02 Jul 12:15:34.717 [debug] [udp_request.c:308] client to proxy cb
[31760] 02 Jul 12:15:34.775 [debug] [udp_request.c:444] resolver to proxy cb
^C
root@fvz-rec-hk-nt-01:~# /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:443 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -VVV
[31761] 02 Jul 12:15:36.054 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74
[31761] 02 Jul 12:15:36.055 [warning] [debug.c:93] Crashed by signal: 11
[31761] 02 Jul 12:15:36.055 [warning] [debug.c:94] --- STACK TRACE
[31761] 02 Jul 12:15:36.055 [warning] [debug.c:96] Failed assertion: <no assertion failed> (<no file>:0)
[31761] 02 Jul 12:15:36.055 [warning] [debug.c:98] --- STACK TRACE
[0x407fd8]
/lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x273a)[0x7ff9c4310aaa]
/lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x273a)[0x7ff9c4310aaa]
/lib/x86_64-linux-gnu/libc.so.6(vsnprintf+0xa2)[0x7ff9c4336512]
[0x406ea3]
[0x40684b]
[0x403831]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7ff9c42e9ead]
[0x403c9d]
Segmentation fault
```

Here is an strace of the command:
https://scr.meo.ws/paste/2015-07-02-14-18-19-O0YvcDhn.txt

GDB:

```
root@fvz-rec-hk-nt-01:~# gdb --args /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:443 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -VVV
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/sbin/dnscrypt-wrapper...done.
(gdb) r
Starting program: /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:443 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws -VVV
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[32063] 02 Jul 12:20:49.385 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff716aaaa in vfprintf () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff716aaaa in vfprintf () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7190512 in vsnprintf () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000406ea3 in _logger_with_fileline (priority=priority@entry=3, fmt=fmt@entry=0x4092ea "Unable to bind (TCP): %s", file=file@entry=0x409233 "tcp_request.c", line=line@entry=418) at logger.c:58
#3  0x000000000040684b in tcp_listener_bind (c=c@entry=0x7fffffffe2b0) at tcp_request.c:418
#4  0x0000000000403831 in main (argc=<optimized out>, argv=0x7fffffffeab8) at main.c:428
(gdb) kill
Kill the program being debugged? (y or n) y
(gdb) quit
```

So from what I can see, it's crashing while trying to bind to the requested IP/Port AND failed to print an error message(?).

But there is no process listening on that IP/Port pair:

```
root@fvz-rec-hk-nt-01:~# ss -ln
State   Recv-Q  Send-Q  Local Address:Port                   Peer  Address:Port
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:5353   :::*
LISTEN  0       128     151.236.20.236:5353                  *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:1194   :::*
LISTEN  0       128     151.236.20.236:1194                  *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:8080   :::*
LISTEN  0       128     151.236.20.236:8080                  *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:53     :::*
LISTEN  0       128     151.236.20.236:53                    *:*
LISTEN  0       128     ::1:53                               :::*
LISTEN  0       128     127.0.0.1:53                         *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:54     :::*
LISTEN  0       128     151.236.20.236:54                    *:*
LISTEN  0       128     :::22                                :::*
LISTEN  0       128     *:22                                 *:*
LISTEN  0       128     127.0.0.1:9050                       *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:443    :::*
LISTEN  0       128     *:2812                               *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:1053   :::*
LISTEN  0       128     151.236.20.236:1053                  *:*
LISTEN  0       128     2a03:f80:852:151:236:20:236:1:27015  :::*
LISTEN  0       128     151.236.20.236:27015                 *:*
root@fvz-rec-hk-nt-01:~# /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:443 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -VV
V
[32088] 02 Jul 12:22:24.073 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74
[32088] 02 Jul 12:22:24.073 [warning] [debug.c:93] Crashed by signal: 11
[32088] 02 Jul 12:22:24.073 [warning] [debug.c:94] --- STACK TRACE
[32088] 02 Jul 12:22:24.073 [warning] [debug.c:96] Failed assertion: <no assertion failed> (<no file>:0)
[32088] 02 Jul 12:22:24.074 [warning] [debug.c:98] --- STACK TRACE
[0x407fd8]
/lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x273a)[0x7f8200aa5aaa]
/lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x273a)[0x7f8200aa5aaa]
/lib/x86_64-linux-gnu/libc.so.6(vsnprintf+0xa2)[0x7f8200acb512]
[0x406ea3]
[0x40684b]
[0x403831]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f8200a7eead]
[0x403c9d]
Segmentation fault
```

But, this appears to only happen on this server with this IP and this Port only; other IPs or Ports seem to work fine:

```
root@fvz-rec-hk-nt-01:~# /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:12345 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -
VVV
[32123] 02 Jul 12:28:54.848 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74
^C
root@fvz-rec-hk-nt-01:~# /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:12345 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -VVV
[32124] 02 Jul 12:28:59.673 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74
^C
root@fvz-rec-hk-nt-01:~# /usr/local/sbin/dnscrypt-wrapper -U -r 127.0.0.1:53 -a 151.236.20.236:12345 --crypt-secretkey-file=/etc/dnscrypt-wrapper/crypt_secret.key --crypt-publickey-file=/etc/dnscrypt-wrapper/crypt_public.key --provider-cert-file=/etc/dnscrypt-wrapper/dnscrypt.cert --provider-name=2.fvz-rec-hk-nt-01.dnscrypt-cert.meo.ws  -VVV
[32129] 02 Jul 12:29:01.920 [info] [main.c:318] Crypt public key fingerprint: C311:BD17:3CE5:D12F:4CE8:033B:275A:DF44:7EAC:D207:32DB:FF6E:DE22:3E03:537A:7B74
^C
```

**Comment by Cofyc** [comment]
Hi,

Do you have another dnscrypt-wrapper process running? It crashes because it cannot bind at the exact same IP+Port. (It should print error message and exit. This is a bug I fixed in #5aae3bf.)

Which OS (and distribution & version if linux) do you use?

**Comment by Fusl** [comment]
Hi,

as already said, there is no other dnscrypt-wrapper process running on this port, BUT there are 13 other dnscrypt-wrapper processes running on different IP/Port pairs.

OS is Debian 7.8 running with 3.2.0-4-amd64 kernel. libc6 is version 2.13-38+deb7u8. All that inside a KVM virtual machine with VirtIO network card (no idea if this info helps a little bit).

**Comment by Cofyc** [comment]
Hi,

I tested on Debian 7.6 64 bit with latest master branch, and the problem is gone.

Can you try latest master branch again? Let me know if you have problem or not.

**Comment by Fusl** [comment]
I rebooted the machine just to check and see if the leap second (2015-07-01) may have caused a kernel bug but apparently the problem still persists, even with the latest master branch build.

**Comment by cofyc** [comment]
Please update to latest [0.3 release](https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3).
